### ISSUE TITLE
显示屏SPI驱动由软件模式改为硬件模式

### ISSUE THREAD

**Issue by armfly** [armfly/H7-TOOL_STM32H7_App#6]
显示器硬件接口挂在硬件spi接口。目前移植的软件采用软件gpio模拟spi。可以使用硬件spi提高刷屏性能。CPU的MISO引脚可以配置为MOSI功能。

**Comment by 596142041** [comment]
已经修改为硬件SPI接口.稍后提交

**Comment by armfly** [comment]
好的。SPI CLK时钟最高可以到多少M

**Comment by 596142041** [comment]
目前是2分频,刷新还可以接受

**Comment by armfly** [comment]
实测硬件模式刷屏速度比软件慢了很多。显示函数中的单字节写入必须转换为整块连续写入才能提高效率。需要继续优化。

**Comment by armfly** [comment]
目前的固件已支持SPI DMA硬件刷屏，速度很快。
